### ISSUE TITLE
Chrome/Brave: "ObjectMultiplex - malformed chunk without name" error

### ISSUE THREAD

**Issue by polyclick** [amandaghassaei/canvas-capture#8]
Hi

After I import CanvasCapture in my code and run it in chrome/brave it returns thousands of warning & eventually crashes.

```
ObjectMultiplex - malformed chunk without name "33,249,4,9,0,0,0,0,44,0,0,0,0,0,0,0,0,135,0,0,0,1,1,1,2,2,2,3,3,3,4,4,4,5,5,5,6,6,6,7,7,7,8,8,8,9,9,9,10,10,10,11,11,11,12,12,12,13,13,13,14,14,14,15,15,15,16,16,16,17,17,17,18,18,18,19,19,19,20,20,20,21,21,21,22,22,22,23,23,23,24,24,24,25,25,25,26,26,26,27,27,27,28,28,28,29,29,29,30,30,30,31,31,31,32,32,32,33,33,33,34,34,34,35,35,35,36,36,36,37,37,37,38,38,38,39,39,39,40,40,40,41,41,41,42,42,42,43,43,43,44,44,44,45,45,45,46,46,46,47,47,47,48,48,48,49,49,49,50,50,50,51,51,51,52,52,52,53,53,53,54,54,54,55,55,55,56,56,56,57,57,57,58,58,58,59,59,5
```

Adding `import { CanvasCapture } from 'canvas-capture'` to my code is enough to trigger the errors.
Firefox doesn't show these warnings, so might be browser specific?

I tried importing without `{}` to no avail.

Other details:
- Webpack 5.70
- Canvas-capture 2.0.0
- Chrome version 100.0.4896.60 (In brave: chromium with same version)

**Comment by polyclick** [comment]
Further investigation:

This error seems to get triggered in combination with a chrome extension: MetaMask
When I disable the extension, no warnings are shown.

I think this has to do with how CanvasCapture is exported/imported as a module, maybe something goes wrong and injected scripts/modules like extensions can't work properly anymore.

**Comment by polyclick** [comment]
Yes, I have the same error on the demo page.

Indeed, seems that the warning is from MetaMask. Not sure why it errors in combination with CanvasCapture. Maybe some global object? Or a prototype override? This is the error: https://github.com/MetaMask/object-multiplex/blob/b49343570d5b14d98d6e6867b33d9cfb7fab879f/src/ObjectMultiplex.ts#L89

I tried adding the headers, same problem.

**Comment by amandaghassaei** [comment]
it's tough to figure out which canvas-capture dependencies is causing this from looking at the MetaMask code.  some suspects are the gif writing code (uses webworkers, dependency of CCapture.js) and ffmpeg-wasm.

I didn't see any uses of toBlob in MetaMask, so I don't think it's the toBlob polyfill I added from `mdn-polyfills/HTMLCanvasElement.prototype.toBlob`

I just pushed version 2.0.1 to npm with some changes to the way ffmpeg is imported, maybe that fixes this issue?  At the very least, I was able to get the build size of this library down a bit.

Hope that fixes this issue, otherwise, I don't think there's more I can do unfortunately!

**Comment by polyclick** [comment]
Thanks for the reply & work  @amandaghassaei — I've upgraded to `2.0.1` but the the problem remains. Big thanks for the effort tho, it's not an easy problem to find :(

For now I'll just disable the extension on localhost. There's an extension for that 🤣

**Comment by amandaghassaei** [comment]
sounds good, thanks for testing.  hopefully it gets resolved at some point!  closing this for now.
